### ISSUE TITLE
UIWebView deprecation

### ISSUE THREAD

**Issue by Ashoat** [wix/react-native-keyboard-tracking-view#28]
Apple is now attaching this warning to any app store uploads whose binaries contain the string `UIWebView`:

> **ITMS-90809: Deprecated API Usage** - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

For now, it's just a warning, and doesn't stop the upload from going through. I don't have enough context on how XCode/App Store Connect finds the references to `UIWebView` to know if gating the `UIWebView` stuff behind a preprocessor macro would work, but I suspect it would.

**Comment by tmhoang1904** [comment]
On Apr 2020, apple will not accept new apps with UIWebview anymore, and Dec 2020 will not accept updating app. So will this issue be resolved?

**Comment by milesscherrer** [comment]
Anything new on this? Not proficient in how to fix it myself :/

**Comment by nikbelikov** [comment]
No hope...

**Comment by nikbelikov** [comment]
15 марта 2020
Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020.

14 марта 2020
Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020.

10 марта 2020
Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020.

8 ноября 2019
Apple will stop accepting submissions of apps that use UIWebView APIs.

**Comment by jordoh** [comment]
@nikbelikov - one option is to use [patch-package](https://github.com/ds300/patch-package) to remove the UIWebView references in KeyboardTrackingViewManager.m in your project - example content of `patches/react-native-keyboard-tracking-view+5.6.1.patch`:
```
diff --git a/node_modules/react-native-keyboard-tracking-view/lib/KeyboardTrackingViewManager.m b/node_modules/react-native-keyboard-tracking-view/lib/KeyboardTrackingViewManager.m
index 800bd35..b926f70 100644
--- a/node_modules/react-native-keyboard-tracking-view/lib/KeyboardTrackingViewManager.m
+++ b/node_modules/react-native-keyboard-tracking-view/lib/KeyboardTrackingViewManager.m
@@ -128,35 +128,6 @@ - (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
     return subview;
 }
 
--(void)_swizzleWebViewInputAccessory:(UIWebView*)webview
-{
-    UIView* subview;
-    for (UIView* view in webview.scrollView.subviews)
-    {
-        if([[view.class description] hasPrefix:@"UIWeb"])
-        {
-            subview = view;
-        }
-    }
-    
-    if(_newClass == nil)
-    {
-        NSString* name = [NSString stringWithFormat:@"%@_Tracking_%p", subview.class, self];
-        _newClass = NSClassFromString(name);
-        
-        _newClass = objc_allocateClassPair(subview.class, [name cStringUsingEncoding:NSASCIIStringEncoding], 0);
-        if(!_newClass) return;
-        
-        Method method = class_getInstanceMethod([UIResponder class], @selector(inputAccessoryView));
-        class_addMethod(_newClass, @selector(inputAccessoryView), imp_implementationWithBlock(^(id _self){return _observingInputAccessoryView;}), method_getTypeEncoding(method));
-        
-        objc_registerClassPair(_newClass);
-    }
-    
-    object_setClass(subview, _newClass);
-    [subview reloadInputViews];
-}
-
 -(void)layoutSubviews
 {
     [super layoutSubviews];
@@ -235,10 +206,6 @@ - (void)initializeAccessoryViewsAndHandleInsets
         {
             [self setupTextView:(UITextView*)subview];
         }
-        else if ([subview isKindOfClass:[UIWebView class]])
-        {
-            [self _swizzleWebViewInputAccessory:(UIWebView*)subview];
-        }
     }
     
     for (RCTScrollView *scrollView in rctScrollViewsArray)
```
